services:
  nginx:
    container_name: nginx
    image: nginx:1.27.1
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
    ports:
      - 80:80
    volumes:
      - ./templates-initiate:/etc/nginx/templates
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:v2.11.0
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${KC_HOSTNAME}
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
